#! /bin/sh

pulseaudio -k
pulseaudio --daemonize
xset m 1/1
xsetroot -cursor_name left_ptr
sxhkd &
polybar -r primary &
dunst &
picom -cb
dropbox &
udiskie &
blueman-applet &
xss-lock -- i3lock -nf -B 8 --indicator &
feh --bg-scale ~/.config/wallpaper
conky

bspc monitor -d 1 2 3 4 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam state=pseudo_tiled
bspc rule -a Virt-manager state=pseudo_tiled
